spring:
  application:
    name: xml-workflow-search-benchmark

  datasource:
    url: jdbc:postgresql://localhost:5434/xml_benchmark
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

search:
  elasticsearch:
    base-url: http://localhost:9201
    index-name: workflow-documents

  opensearch:
    base-url: http://localhost:9200
    index-name: workflow-documents

  solr:
    base-url: http://localhost:8983/solr
    collection-name: workflow-documents









